### ISSUE TITLE
[java] Expected attribute name

### ISSUE THREAD

**Issue by acarioni** [HaxeFoundation/dox#299]
I’m using dox 1.6.0 with haxe 4.3.0-rc.1+a49b191 on a multi-target project.
When I try to generate the documentation for the java target, I get the following error:

```
Using Node.js version of dox...
Parsing bin/docs/java.xml
src/dox/Dox.hx:143: Error while parsing bin/docs/java.xml

/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:2944
			throw haxe_Exception.thrown(err);
			^
<ref *1> Error: haxe.xml.XmlParserException: Expected attribute name at line 71314 char 23
    at new haxe_ValueException (/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:6018:17)
    at Function.haxe_Exception.thrown (/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:4405:11)
    at parseFile (/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:2944:25)
    at Function.dox_Dox.run (/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:2961:3)
    at Function.dox_Dox.main (/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:2914:10)
    at /Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:19317:9
    at Object.<anonymous> (/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib/run.js:19318:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  __previousException: undefined,
  __nativeException: [Circular *1],
  __skipStack: 2,
  value: {
    xml: ...,
    message: 'Expected attribute name',
    position: 2976744,
    lineNumber: 713
[java.xml.zip](https://github.com/HaxeFoundation/dox/files/8998821/java.xml.zip)
14,
    positionAtLine: 23
  }
}
Failed to invoke `haxelib run-dir dox "/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib" -i bin/docs/java.xml -o bin/pages` because Error: Command failed: haxelib run-dir dox "/Users/acarioni/haxe/haxe_libraries/dox/1.6.0/haxelib" -i bin/docs/java.xml -o bin/pages
```

**Comment by sebthom** [comment]
I cannot reproduce this using 4.3.0-rc.1+1cbe856. Is it still an issue?
